apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: datacenter-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/supervision_db
            - name: SPRING_DATASOURCE_USERNAME
              value: supervision_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PROMETHEUS_URL
              value: http://prometheus:9090
            - name: MAIL_USER
              value: salmafallahi2@gmail.com
            - name: MAIL_PASSWORD
              value: udfs fcnh mnzj cyij
            - name: APP_JWT_SECRET
              value: votre-cle-super-secrete-pour-jwt-2024!