apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: datacenter
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/salmafallahi/datacenter-backend:302e68893f6c7b58eafb916af15691e5b27fdf23
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/supervision_db
            - name: SPRING_DATASOURCE_USERNAME
              value: supervision_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PROMETHEUS_URL
              value: http://prometheus:9090
            - name: MAIL_USER
              value: salmafallahi2@gmail.com
            - name: MAIL_PASSWORD
              value: udfs fcnh mnzj cyij
            - name: APP_JWT_SECRET
              value: votre-cle-super-secrete-pour-jwt-2024!
