apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: datacenter
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_YOUR_JWT_SECRET"
  MAIL_PASSWORD: "REPLACE_WITH_YOUR_EMAIL_PASSWORD"