apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: datacenter
spec:
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ml
          image: datacenter-ml-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
