apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml
          image: ghcr.io/salmafallahi/datacenter-ml:latest
          ports:
            - containerPort: 8000