apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datacenter-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salmafallahi/datacenter-monitoring.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: datacenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
