name: CD - Deploy to Minikube

on:
  workflow_run:
    workflows: ["CI Backend", "CI Frontend", "CI ML Service"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/postgres/
          kubectl apply -f k8s/ml-service/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/prometheus/
          kubectl apply -f k8s/ingress.yaml
          kubectl get all -n datacenter